"""add accounts

Revision ID: c1a2b5902505
Revises: 06632a42beec
Create Date: 2025-06-12 16:10:28.257952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a2b5902505'
down_revision: Union[str, None] = '06632a42beec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('responsibility_duties', sa.String(), nullable=False),
    sa.Column('qualification_skills', sa.JSON(), nullable=False),
    sa.Column('work_environment', sa.String(), nullable=False),
    sa.Column('salary_benefits', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobs')
    op.add_column('applications', sa.Column('resume_path', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('cover_letter_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_path')
    op.drop_column('applications', 'resume_path')
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', name='employmenttype'), autoincrement=False, nullable=False),
    sa.Column('salary_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('benefits', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_id', name='jobs_pkey')
    )
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
